handle Exception on the highest level
allyotov/learn-homework-1 pull request #1
Opened 2021-09-07 11:45 UTC by allyotov

Updated 7th task, please, merge.

2021-09-07 13:46 UTC, vppuzakov requested changes

2021-09-07 13:46 UTC, vppuzakov commented on 7_exception2.py
> +    finally:
**finally** тут лишний (еще и пустой)

2021-09-07 13:46 UTC, vppuzakov commented on 7_exception2.py
> +    # raise DeprecationWarning('Deprecation Test is running now;')
закомментированных строчек лучше тоже не иметь в коде

2021-09-07 13:46 UTC, vppuzakov commented on 7_exception2.py
> +        deprecation_test_case()
Попробуй спровоцировать какой-либо другой exception, вроде деления на ноль

2021-09-07 14:05 UTC, allyotov commented on 7_exception2.py
> +    finally:
Заполнил его распечаткой сообщения о завершении выполнения программы. См. новый коммит выше.

2021-09-07 14:05 UTC, allyotov commented on 7_exception2.py
> +    # raise DeprecationWarning('Deprecation Test is running now;')
Удалил мусорный комментарий. См. новый коммит выше.

2021-09-07 14:05 UTC, allyotov commented on 7_exception2.py
> +        deprecation_test_case()
Добавил тест на zero division error. См. новый коммит выше.

2021-09-08 09:40 UTC, vppuzakov approved these changes

2021-09-08 14:02 UTC, merged